# theme: minima
remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# skin: dark
# Available skins are:
# classic (Default)
# dark Dark
# auto
# solarized-light
# solarized-dark
# solarized
  
title: Sonyah G. Seiden - Portfolio
author: Sonyah G. Seiden

description: >
  Learn more about my academic & professional background.
   See examples of my technical capabilities with featured projects.

#social_links
# - { platform: github, user_url: "https://github.com/sonyah-hawaii" }
# - { platform: linkedin, user_url: "https://www.linkedin.com/in/sonyahseiden/" }
# - { platform: tableau, user_url: "https://public.tableau.com/app/profile/sonyah/vizzes/" }